Date modal contest fix
esgiprojetninja/fbapp pull request #26
Opened 2017-01-07 14:17 UTC by dydyFos

DRY 101 not respected with those two funcs:
addIfInferior &&  uiDateFormater.
They exist in both:
resources/assets/js/lib/pictureGame/ui/AdminContests.js
&&
resources/assets/js/lib/pictureGame/ui/ContestModalForm.js

2017-01-07 17:24 UTC, Rolandkuku commented
C'est quoi cette avalanche de binaires ?

2017-01-07 17:27 UTC, grollec requested changes

2017-01-07 17:27 UTC, Rolandkuku commented on database/migrations/2014_10_12_000000_create_users_table.php
> -            $table->string('email')->unique();
Donc, l'email n'est plus unique ?

2017-01-07 17:27 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/container/SubMenu.js
> +    return Object.assign({}, state);
Sur le rest de l'app on utilise l'object spread operator. Tu préfère Object.assign() ?

2017-01-07 17:27 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/container/SubMenu.js
> +export default SubMenu
Point virgule

2017-01-07 17:29 UTC, dydyFos commented on resources/assets/js/lib/pictureGame/container/SubMenu.js
> +export default SubMenu
Okaaay

2017-01-07 17:31 UTC, dydyFos commented on database/migrations/2014_10_12_000000_create_users_table.php
> -            $table->string('email')->unique();
L'app ne voit pas mon email j'y ai mis un ->default("null") à la place sinon j'suis incapable de me connecter. Faudrait que l'identification se fasse par id_fb

2017-01-08 09:26 UTC, Rolandkuku commented on database/migrations/2014_10_12_000000_create_users_table.php
> -            $table->string('email')->unique();
C'est pas possible de chaîner null et unique ?

2017-01-08 14:23 UTC, dydyFos commented on database/migrations/2014_10_12_000000_create_users_table.php
> -            $table->string('email')->unique();
done

2017-01-08 14:56 UTC, grollec requested changes
Ce serait cool d'enlever tous ces binaires.

2017-01-09 16:44 UTC, grollec approved these changes

2017-01-09 16:53 UTC, dydyF05 reviewed
Manque quoi ?

2017-01-09 20:44 UTC, merged

2017-01-09 20:44 UTC, Rolandkuku commented
Manque rien. J'étais à l'apéro, je ne peux pas tout faire.