Get user fb albums
esgiprojetninja/fbapp pull request #33
Opened 2017-01-26 18:04 UTC by dydyFos

2017-01-27 13:16 UTC, grollec requested changes
Faut absolument factoriser le fichier d'UI + 2/3 truc.
Mais sinon : gg wp

2017-01-27 13:16 UTC, grollec commented on app/Http/Controllers/Api/v1/ParticipantController.php
> +    }
remove this

2017-01-27 13:16 UTC, grollec commented on app/Http/Controllers/Api/v1/ParticipantController.php
> +        if ( app('App\Http\Controllers\Api\v1\ContestController')->currentlyActive() ) {
Move method into a model

2017-01-27 13:16 UTC, grollec commented on app/Http/Controllers/Api/v1/ParticipantController.php
> +        $user = app('App\Http\Controllers\Api\v1\AuthController')->getMe()->getData()->user;
same

2017-01-27 13:16 UTC, grollec commented on app/Http/Controllers/Controller.php
> +    protected function tryJsonDecode($s){
Remove this ?

2017-01-27 13:16 UTC, grollec commented on resources/assets/js/lib/pictureGame/actions/participantActions.js
> +const receiveNotAddedPhotoContest = ({added, msg}) => {
added

2017-01-27 13:16 UTC, grollec commented on resources/assets/js/lib/pictureGame/actions/participantActions.js
> +const receiveNotAddedPhotoContest = ({added, msg}) => {
?

2017-01-27 13:16 UTC, grollec commented on resources/assets/js/lib/pictureGame/reducers/participant.js
> +      state.currentContest.push({photo_id: action.photo_id, source: action.source, user_fbid: action.user_fbid, photo_votes: action.photo_votes});
Ne pas muter le state

2017-01-27 13:16 UTC, grollec commented on resources/assets/js/lib/pictureGame/reducers/participant.js
> +      state.currentContest = state.currentContest.filter( par => par.user_fbid != action.user_fbid );
same

2017-01-27 13:16 UTC, grollec commented on resources/assets/js/lib/pictureGame/reducers/user.js
> +      const s = {...state};
?

2017-01-27 13:16 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/reducers/user.js
> +      const oldState = {...state};
TODO : refacto

2017-01-27 13:16 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +      // console.log('Component DID UPDATE!', this.props)
coucou

2017-01-27 13:16 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +              //jQuery('.home-carousel-btn-wrapper').fadeOut();
prout

2017-01-27 13:16 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +      jQuery('html,body').animate({scrollTop: jQuery(selector).offset().top},'slow');
Dans le reste de l'app, on import jquery comme ça : `import $ from "jquery";`

2017-01-27 13:16 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +      // Au cas où la cover n'ait pas été trouvée par le call API
Pas de Français (dans le code)

2017-01-27 13:16 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +
Et si ont décomposait ce fichier ?

2017-01-28 11:40 UTC, dydyFos commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +              //jQuery('.home-carousel-btn-wrapper').fadeOut();
On s'demande qui à mis cette @"#;~ dans le code :D

2017-01-28 11:40 UTC, dydyFos commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +      // Au cas où la cover n'ait pas été trouvée par le call API
ay sir

2017-01-28 14:25 UTC, dydyFos commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +
En différents UI-Component ?

2017-01-30 11:07 UTC, merged