Post personnal photo
esgiprojetninja/fbapp pull request #37
Opened 2017-02-05 20:08 UTC by dydyFos

@Rolandkuku j'ai utilisé un $.ajax dans "resources/assets/js/lib/pictureGame/utils/FacebookLoader.js" au lieu de passer par this.fb

2017-02-05 20:17 UTC, grollec requested changes
Gros taff

2017-02-05 20:17 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/actions/participantActions.js
> +        type: types.RECEIVED_FB_PHOTO_UPLOAD_FAIL,
C'est une action, pas un événement => on parle au présent.

2017-02-05 20:17 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/reducers/participant.js
> +        case pTypes.RECEIVED_FB_PHOTO_UPLOAD_FAIL:
Présent.

2017-02-05 20:17 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/Notice.js
> +        if ( this.props.leaveAction ){this.props.leaveAction()};
Webpack va minifier ton code, pas besoin de foutre ça sur un ligne. 
Il faut privilégier la lisibilité.

2017-02-05 20:23 UTC, Rolandkuku commented
![screen shot 2017-02-05 at 21 22 45](https://cloud.githubusercontent.com/assets/6169736/22629605/467e9cd6-ebe9-11e6-9fb6-4e73d68056ee.png)

2017-02-05 20:23 UTC, Rolandkuku commented
Quand je veux up une photo.

2017-02-05 20:40 UTC, Rolandkuku commented
![screen shot 2017-02-05 at 21 39 38](https://cloud.githubusercontent.com/assets/6169736/22629706/a34e702e-ebeb-11e6-8844-bf1ce76f3e62.png)
Le bouton annuler ne fonctionne pas.

2017-02-05 22:21 UTC, dydyFos commented on resources/assets/js/lib/pictureGame/ui/Notice.js
> +        if ( this.props.leaveAction ){this.props.leaveAction()};
Heard

2017-02-06 09:00 UTC, Rolandkuku commented
![screen shot 2017-02-06 at 09 59 32](https://cloud.githubusercontent.com/assets/6169736/22640457/06333140-ec53-11e6-94e3-c3c5070d7055.png)

Pb 1 : Il n'y a pas d'indication pour me dire que je peux aussi mettre une photo sans le drag n drop.
Pb 2 : La photo sélectionnée dépasse.

2017-02-06 09:08 UTC, grollec approved these changes

2017-02-06 09:08 UTC, merged