Feature/teddy admin view
esgiprojetninja/fbapp pull request #38
Opened 2017-02-06 15:20 UTC by GoRFy

2017-02-06 15:37 UTC, grollec requested changes

2017-02-06 15:37 UTC, Rolandkuku commented on public/mockup.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Ça sert à quoi ça ?

2017-02-06 15:37 UTC, Rolandkuku commented on public/mockup.svg
> +</svg>
Et l'image en dessous ?

2017-02-06 15:37 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/actions/contestActions.js
> +        colorGallery: colorGallery
En ES6, tu peux l'écrire comme ça : 
```
return {
  type: actionTypes.CHANGE_COLOR_GALLERY,
  colorGallery
}
```

2017-02-06 15:37 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/actions/contestActions.js
> +        colorGallery: colorGallery
Si le nom de ton attribut est le même que celui de ta variable.

2017-02-06 15:37 UTC, Rolandkuku commented on database/migrations/2017_02_06_140634_create_uisettings_table.php
> +            $table->string('imgArray');
Pas de CamelCase dans la db

2017-02-06 15:37 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/reducers/contest.js
> +    colorGallery: "#00BCD4",
Il y a pas moyen de mettre des variables à la place ?

2017-02-06 15:38 UTC, Rolandkuku commented
Il y a des endroits qui ne sont pas très beaux mais bravo pour le gros taff !

2017-02-06 15:48 UTC, teddymeksavanh commented on public/mockup.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Je vais delete le svg, en vrai j'en ai pas besoin dans le public

2017-02-06 15:48 UTC, teddymeksavanh commented on public/mockup.svg
> +</svg>
Je vais delete le svg, en vrai j'en ai pas besoin dans le public

2017-02-06 15:49 UTC, teddymeksavanh commented on resources/assets/js/lib/pictureGame/actions/contestActions.js
> +        colorGallery: colorGallery
Ok merci, je me disais j'avais vu ça sur redux en plus

2017-02-06 16:03 UTC, teddymeksavanh commented on resources/assets/js/lib/pictureGame/reducers/contest.js
> +    colorGallery: "#00BCD4",
Je peux mettre ça dans une constante plus haut ouai

2017-02-07 00:25 UTC, teddymeksavanh commented on resources/assets/js/lib/pictureGame/reducers/contest.js
> +    colorGallery: "#00BCD4",
Enfin de compte non, j'need une string

2017-02-07 07:11 UTC, grollec approved these changes
LGTM

2017-02-07 07:11 UTC, grollec commented on app/UISettings.php
> +        'colorOne',
Faut adapter ça du coup.

2017-02-07 07:11 UTC, Rolandkuku commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +    showmsg() {
?

2017-02-07 07:11 UTC, merged

2017-02-07 09:49 UTC, teddymeksavanh commented on app/UISettings.php
> +        'colorOne',
Ok c'est good après avoir push

2017-02-07 09:49 UTC, teddymeksavanh commented on resources/assets/js/lib/pictureGame/ui/HomeCarousel.js
> +    showmsg() {
Ok c'est good après avoir push